Laboratorio3/Laboratorio3/Models/PersonaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class PersonaModel
    {
        //Propiedades: cuando se instancia una persona se puede hacer persona. Peso=valor

        public string Nombre{get; set;}
        public int Id {get; set;}
        public double Peso { get; set; }
        public double Estatura { get; set; }

        //Constructores(no es indispensable en este caso)

        public PersonaModel() {
            this.Nombre = "Sin nombre";
            this.Id = 0;
            this.Peso = 0.0;
            this.Estatura = 0.0;
        }

        public PersonaModel(int Id, string Nombre, double Peso, double Estatura) {
            this.Nombre = Nombre;
            this.Id = Id;
            this.Peso = Peso;
            this.Estatura = Estatura;
        }
    }
}

Laboratorio3/Laboratorio3/Controllers/CalculadoraIMCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio3.Models;


namespace Laboratorio3.Controllers
{
    public class CalculadoraIMCController : Controller
    {
        public ActionResult ResultadoAleatorioIMC()
        {
            PersonaModel[] lista = new PersonaModel[30];
            double[] ListaIMC = new double[30];
            Random random = new Random();
            for (int f = 0; f < 30; f++)
            {
                double altura = GetRandomNumber(random,1.0, 2.0);
                double peso = GetRandomNumber(random, 20.0, 150.0);
                PersonaModel persona = new PersonaModel(f, "Sin nombre", peso, altura);
                lista[f] = persona;
                double IMC = persona.Peso / (persona.Estatura * persona.Estatura);
                ListaIMC[f] = IMC;
                //ViewBag.IMC = IMC;
               // ViewBag.persona = persona;
            }
            ViewBag.lista = lista;
            ViewBag.listaIMC = ListaIMC;
            return View();
        }

        public ActionResult ResultadoAleatorioPreubaIMC()
        {
            PersonaModel persona = new PersonaModel(1, "Cristiano Ronaldo", 84.0, 1.87);
            double IMC = persona.Peso / (persona.Estatura * persona.Estatura);
            ViewBag.IMC = IMC;
            ViewBag.persona = persona;
            return View();
        }

        public double GetRandomNumber(Random random,double minimum, double maximum)
        {
            
            return random.NextDouble() * (maximum - minimum) + minimum;
        }
    }
}

Laboratorio3/Laboratorio3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Laboratorio3/Laboratorio3/Views/CalculadoraIMC/ResultadoAleatorioIMC.cshtml
@{ 
    ViewBag.Title = "IMC aleatorio";
}

<!DOCTYPE html>
<html>
    <head>
        <title>Resultado IMC </title>
        <meta charset=" utf-8"/>
        <!--Esto es un comentario-->
        <!--en el head se coloca informacion que es para el navegador, scripts, css...-->
    </head>
    <body>
        <!--aqui inicia el cuerpo de la pagina que se esta creando(la vista)-->
        <h1>Resultado</h1>

        <div class="seccion_1" id="s2">
            <ul>
                <li>Enlace https://github.com/VictorB8/Laboratorio3.git </li>

                <li>IMC menor que 18,5 -> peso insuficiente</li>
                <li>IMC 18,5 y 24.9 -> peso normal</li>
                <li>IMC mayor que 25 -> sobrepeso</li>
            </ul>
            <hr />
        </div>

        <div class="section_2" id="s3">
            <a href="/Home" class="btn btn-info">Boton de vuelta al inicio</a>
        </div>

        <div class="seccion_3" id="s1">

            <table class="table">
                <
                <tr>

                    <th>ID</th>

                    <th>Nombre</th>

                    <th>Peso</th>

                    <th>Altura</th>

                    <th>IMC</th>

                </tr>



                @foreach (Laboratorio3.Models.PersonaModel P in ViewBag.lista)
                {
                    <tr>
                        <td>@P.Id</td>
                        <td>@P.Nombre </td>
                        <td>@P.Peso</td>
                        <td>@P.Estatura </td>
                        @if (ViewBag.listaIMC[P.Id] > 18.5 && ViewBag.listaIMC[P.Id] < 24.9)
                        {
                            <td style="color:green;">@ViewBag.listaIMC[P.Id]</td>
                        }
                        else
                        {
                            <td style="color:red;">@ViewBag.listaIMC[P.Id]</td>
                        }
                    </tr>
                }


            </table>
            <hr />
        </div>





    </body>
</html>

Laboratorio3/Laboratorio3/Views/CalculadoraIMC/ResultadosAleatoriosPreubaIMC.cshtml
@{
    ViewBag.Title = "IMC";
}

<!DOCTYPE html>
<html>
<head>
    <title>ResultadoAleatorioIMC </title>
    <meta charset=" utf-8" />
    <!--Esto es un comentario-->
    <!--en el head se coloca informacion que es para el navegador, scripts, css...-->
</head>
<body>
    <!--aqui inicia el cuerpo de la pagina que se esta creando(la vista)-->
    <h1>Resultado</h1>

    <div class="seccion_1" id="s1">

        <table class="table-bondered">
            <
            <tr>

                <th>Encabezado 1</th>

                <th>Encabezado 2</th>

                <th>Encabezado 3</th>

            </tr>

            <tr>

                <td>@ViewBag.persona.Nombre</td>

                <td>Fila 1,Columna 2</td>

                <td>Fila 1,Columna 3</td>

            </tr>

            <tr>
                <td>Fila 2,Columna 1</td>

                <td>Fila 2,Columna 2</td>

                <td>Fila 2,Columna 3</td>

            </tr>
        </table>
        <hr />
    </div>

    <div class="seccion_2" id="s2">
        <ul>
            <li>Elemento 1</li>
            <li>Elemento 2</li>
            <li>Elemento 3</li>
        </ul>
        <hr />
    </div>

    <div class="section_3" id="s3">
        <input type="button" value="Soy un Boton" /><hr />
        <a class="btn btn-info">Soy un link que parece boton</a>
    </div>

    <div class="seccion_4">
        @if (ViewBag.IMC > 20)
        {
            <div class="text-success">
                <p>Mensaje</p>
            </div>
        }
        else
        {
            <div class="text-danger">
                <p>Otro mensaje</p>
            </div>
        }
    </div>
</body>
</html>

Laboratorio3/Laboratorio3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Laboratorio3/Laboratorio3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Laboratorio3/Laboratorio3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Laboratorio3/Laboratorio3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Calculadora IMC aleatorios", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("IMC","ResultadoAleatorioIMC","CalculadoraIMC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>